#pragma once
// Tileset
#define TILESET_BBOX_SIDE_LENGTH	16

// Brick
#define BRICK_BBOX_SIDE_LENGTH	16

// Effect
//#define STATE_DESTROYED	99

#define HIT_EFFECT_TIME	150

// Weapon
#define FIREBALL_BBOX_WIDTH		8
#define FIREBALL_BBOX_HEIGHT	8
#define FIREBALL_SPEED			0.15f
#define FIREBALL_TO_RIGHT		0
#define FIREBALL_TO_LEFT		1

#define TAIL_BBOX_WIDTH			9
#define TAIL_BBOX_HEIGHT		6

// Mario
#define MARIO_RUNNING_SPEED						0.23f
#define MARIO_MAX_WALKING_SPEED					0.12f
#define MARIO_RUNNING_ACCELERATION				0.00015f
#define MARIO_WALKING_ACCELERATION				0.00015f
#define MARIO_SMALL_ACCELERATION_SUBTRAHEND		0.00025f
#define MARIO_LARGE_ACCELERATION_SUBTRAHEND		0.0005f
#define INITIAL_LAST_Y							134.0f
#define MARIO_TOO_HIGH_ABOVE					150

#define	MARIO_WAGGING_TAIL_TIME			150
#define	MARIO_SPINNING_TAIL_TIME		375
#define	MARIO_SHOOTING_FIREBALL_TIME	300
#define MARIO_FLYING_TIME				4000//7000
#define MARIO_KICK_TIME					200

#define MARIO_HIGH_JUMP_SPEED_Y		0.275f
#define MARIO_LOW_JUMP_SPEED_Y		0.2f
#define MARIO_JUMP_DEFLECT_SPEED	0.2f
#define MARIO_GRAVITY				0.0006f
#define MARIO_LOW_JUMP_GRAVITY		0.001f
#define MARIO_FLY_GRAVITY			0.00045f
#define MARIO_DIE_DEFLECT_SPEED		0.5f
#define MARIO_FLY_SPEED_Y			0.25f

#define MARIO_STATE_IDLE			0
#define MARIO_STATE_WALKING_RIGHT	100
#define MARIO_STATE_WALKING_LEFT	200
#define MARIO_STATE_JUMP_LOW		300
#define MARIO_STATE_JUMP_HIGH		400
#define	MARIO_STATE_SIT_DOWN		500
#define MARIO_STATE_RUNNING_RIGHT	600
#define MARIO_STATE_RUNNING_LEFT	700
#define MARIO_STATE_FLYING			800
#define MARIO_STATE_STOP			900
#define MARIO_STATE_ATTACK			1000
#define MARIO_STATE_KICK			1100

#define MARIO_STATE_DIE				999

#define MARIO_ANI_BIG_IDLE_RIGHT			0
#define MARIO_ANI_BIG_WALKING_RIGHT			1
#define MARIO_ANI_BIG_RUNNING_RIGHT			2
#define MARIO_ANI_BIG_JUMP_RIGHT			3
#define MARIO_ANI_BIG_SITTING_RIGHT			4
#define MARIO_ANI_BIG_STOP_RIGHT			5
#define MARIO_ANI_BIG_FALLING_RIGHT			6
#define MARIO_ANI_BIG_KICK_RIGHT			67

#define MARIO_ANI_BIG_IDLE_LEFT				7
#define MARIO_ANI_BIG_WALKING_LEFT			8
#define MARIO_ANI_BIG_RUNNING_LEFT			9
#define MARIO_ANI_BIG_JUMP_LEFT				10
#define MARIO_ANI_BIG_SITTING_LEFT			11
#define MARIO_ANI_BIG_STOP_LEFT				12
#define MARIO_ANI_BIG_FALLING_LEFT			13
#define MARIO_ANI_BIG_KICK_LEFT				68

#define MARIO_ANI_SMALL_IDLE_RIGHT			14
#define MARIO_ANI_SMALL_WALKING_RIGHT		15
#define MARIO_ANI_SMALL_RUNNING_RIGHT		16
#define MARIO_ANI_SMALL_JUMP_RIGHT			17
#define MARIO_ANI_SMALL_STOP_RIGHT			18
#define MARIO_ANI_SMALL_KICK_RIGHT			69

#define MARIO_ANI_SMALL_IDLE_LEFT			19
#define MARIO_ANI_SMALL_WALKING_LEFT		20
#define MARIO_ANI_SMALL_RUNNING_LEFT		21
#define MARIO_ANI_SMALL_JUMP_LEFT			22
#define MARIO_ANI_SMALL_STOP_LEFT			23
#define MARIO_ANI_SMALL_KICK_LEFT			70

#define MARIO_RACCOON_ANI_IDLE_RIGHT					24
#define MARIO_RACCOON_ANI_WALK_RIGHT					25
#define MARIO_RACCOON_ANI_RUNNING_RIGHT					26
#define MARIO_RACCOON_ANI_JUMP_RIGHT					27
#define MARIO_RACCOON_ANI_STOP_RIGHT					28
#define MARIO_RACCOON_ANI_SPIN_TAIL_IDLE_RIGHT			29
#define MARIO_RACCOON_ANI_SITTING_RIGHT					30
#define MARIO_RACCOON_ANI_FALLING_RIGHT					31
#define MARIO_RACCOON_ANI_FALLING_WAG_TAIL_RIGHT		32
#define MARIO_RACCOON_ANI_FLYING_UP_RIGHT				33
#define MARIO_RACCOON_ANI_FLYING_DOWN_RIGHT				63
#define MARIO_RACCOON_ANI_WAG_TAIL_WHILE_FLYING_RIGHT	64
#define MARIO_RACCOON_ANI_KICK_RIGHT					71

#define MARIO_RACCOON_ANI_IDLE_LEFT						34
#define MARIO_RACCOON_ANI_WALK_LEFT						35
#define MARIO_RACCOON_ANI_RUNNING_LEFT					36
#define MARIO_RACCOON_ANI_JUMP_LEFT						37
#define MARIO_RACCOON_ANI_STOP_LEFT						38
#define MARIO_RACCOON_ANI_SPIN_TAIL_IDLE_LEFT			39			
#define MARIO_RACCOON_ANI_SITTING_LEFT					40
#define MARIO_RACCOON_ANI_FALLING_LEFT					41
#define MARIO_RACCOON_ANI_FALLING_WAG_TAIL_LEFT			42
#define MARIO_RACCOON_ANI_FLYING_UP_LEFT				43
#define MARIO_RACCOON_ANI_FLYING_DOWN_LEFT				65
#define MARIO_RACCOON_ANI_WAG_TAIL_WHILE_FLYING_LEFT	66
#define MARIO_RACCOON_ANI_KICK_LEFT						72

#define MARIO_FIRE_ANI_IDLE_RIGHT							44
#define MARIO_FIRE_ANI_WALK_RIGHT							45
#define MARIO_FIRE_ANI_RUNNING_RIGHT						46
#define MARIO_FIRE_ANI_JUMP_RIGHT							47
#define MARIO_FIRE_ANI_STOP_RIGHT							48
#define MARIO_FIRE_ANI_SHOOT_FIREBALL_RIGHT					49
#define MARIO_FIRE_ANI_SHOOT_FIREBALL_WHILE_JUMPING_RIGHT	50
#define MARIO_FIRE_ANI_SITTING_RIGHT						51
#define MARIO_FIRE_ANI_FALLING_RIGHT						52
#define MARIO_FIRE_ANI_KICK_RIGHT							73

#define MARIO_FIRE_ANI_IDLE_LEFT							53
#define MARIO_FIRE_ANI_WALK_LEFT							54
#define MARIO_FIRE_ANI_RUNNING_LEFT							55
#define MARIO_FIRE_ANI_JUMP_LEFT							56
#define MARIO_FIRE_ANI_STOP_LEFT							57
#define MARIO_FIRE_ANI_SHOOT_FIREBALL_LEFT					58
#define MARIO_FIRE_ANI_SHOOT_FIREBALL_WHILE_JUMPING_LEFT	59
#define MARIO_FIRE_ANI_SITTING_LEFT							60
#define MARIO_FIRE_ANI_FALLING_LEFT							61
#define MARIO_FIRE_ANI_KICK_LEFT							74

#define MARIO_ANI_DIE		62

#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2
#define MARIO_RACCOON		3
#define MARIO_FIRE			4

#define MARIO_BIG_BBOX_WIDTH		15
#define MARIO_BIG_BBOX_WIDTH_RIGHT	20
#define MARIO_BIG_BBOX_HEIGHT		27
#define MARIO_BIG_BBOX_L			5

#define MARIO_SMALL_BBOX_WIDTH  15
#define MARIO_SMALL_BBOX_HEIGHT 16

#define MARIO_RACCOON_BBOX_WIDTH		15
#define MARIO_RACCOON_BBOX_HEIGHT		28
#define MARIO_RACCOON_BBOX_SIT			9
#define MARIO_RACCOON_BBOX_WIDTH_RIGHT	15
#define MARIO_RACCOON_BBOX_LEFT			7

#define MARIO_FIRE_BBOX_WIDTH	15
#define MARIO_FIRE_BBOX_HEIGHT	27

#define MARIO_BIG_SIT_BBOX_HEIGHT		18
#define MARIO_RACCOON_SIT_BBOX_HEIGHT	19
#define MARIO_FIRE_SIT_BBOX_HEIGHT		18
#define MARIO_SIT_BBOX					9

#define MARIO_UNTOUCHABLE_TIME 2000


// ENEMIES
// cho enemies xài chung deflect speed x và y?
#define ENEMY_STATE_ATTACKED_BY_TAIL			188  // lead to die or sleep
#define ENEMY_STATE_DIE_BY_WEAPON				199
#define ENEMY_STATE_MOVE						200
#define ENEMY_STATE_IDLE						201
#define ENEMY_DEFECT_SPEED_X_CAUSED_BY_TAIL		0.035f
#define ENEMY_DEFECT_SPEED_Y_CAUSED_BY_TAIL		0.28f

// Goomba
#define GOOMBA_MOVE_SPEED_X					0.035f
#define GOOMBA_DEFLECT_SPEED_Y				0.15f
#define GOOMBA_DEFLECT_SPEED_X				0.03f
#define GOOMBA_BBOX_WIDTH					16
#define GOOMBA_BBOX_HEIGHT					16
#define GOOMBA_BBOX_HEIGHT_DIE_BY_CRUSH		9
#define GOOMBA_ANI_MOVE						0
#define GOOMBA_ANI_DIE_BY_CRUSH				1
#define GOOMBA_ANI_DIE_BY_ATTACK_TOOL		2
#define GOOMBA_STATE_DIE_BY_CRUSH			299

// Koopa
#define KOOPA_MOVE_SPEED_X					0.025f
#define KOOPA_SPIN_AND_MOVE_SPEED_X			0.2f
#define KOOPA_DEFLECT_SPEED_Y				0.15f
#define KOOPA_DEFLECT_SPEED_X				0.03f
#define KOOPA_BBOX_WIDTH					16
#define KOOPA_BBOX_HEIGHT					27
#define KOOPA_BBOX_HEIGHT_LAY_VIBRATE_SPIN	16
#define KOOPA_BBOX_WIDTH_VIBRATE			18
#define KOOPA_ANI_MOVE_RIGHT				0
#define KOOPA_ANI_MOVE_LEFT					1
#define KOOPA_ANI_LAY_PRONE					2
#define KOOPA_ANI_LAY_SUPINE				3
#define KOOPA_ANI_VIBRATE_PRONE				4
#define KOOPA_ANI_VIBRATE_SUPINE			5
#define KOOPA_ANI_SPIN_AND_MOVE_PRONE		6
#define KOOPA_ANI_SPIN_AND_MOVE_SUPINE		7
#define KOOPA_STATE_SPIN_AND_MOVE			80

// Red Fire Piranha
#define FIRE_PIRANHA_MOVE_SPEED				0.03f
#define FIRE_PIRANHA_BBOX_WIDTH				16
#define FIRE_PIRANHA_BBOX_HEIGHT			24
#define FIRE_PIRANHA_ANI_FACE_UP_LEFT		0
#define FIRE_PIRANHA_ANI_FACE_DOWN_LEFT		1
#define FIRE_PIRANHA_ANI_FACE_UP_RIGHT		2
#define FIRE_PIRANHA_ANI_FACE_DOWN_RIGHT	3
#define FIRE_PIRANHA_ANI_ATTACK_UP_LEFT		4
#define FIRE_PIRANHA_ANI_ATTACK_DOWN_LEFT	5
#define FIRE_PIRANHA_ANI_ATTACK_UP_RIGHT	6
#define FIRE_PIRANHA_ANI_ATTACK_DOWN_RIGHT	7

// PlayScene
#define SCENE_SECTION_UNKNOWN			-1
#define SCENE_SECTION_TEXTURES			2
#define SCENE_SECTION_SPRITES			3
#define SCENE_SECTION_ANIMATIONS		4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS			6
#define SCENE_SECTION_TILEMAP			7

#define MAX_SCENE_LINE 1024

// list of object type
enum Type
{
	PORTAL = 55,
	MARIO = 0,
	QUESTION_BRICK = 1,
	GOOMBA = 2,
	KOOPA = 3,
	FLOOR = 4,
	COLOR_BOX = 5,
	FIRE_PIRANHA_PLANT = 6,
	PIRANHA_PLANT = 7,
	FIREBALL = 8,
	HAMMER = 9,
	TAIL = 10,
};

enum Category
{
	PLAYER,
	ENEMY,
	MISC,
	ITEM,
	WEAPON,
	EFFECT,
	SCENE,
};